### ISSUE TITLE
Run from within the folder.

### ISSUE THREAD

**Issue by razvanab** [ImmortalPie/ComfyUI-PonySwitch#3]
Can you please make the extension work in its own folder?
It will be easier to update without having to copy the.py file separately.
Thank you.

**Comment by ImmortalPie** [comment]
Sorry I'm not sure what the issue is, I've just tested pulling the repo and it already does put it in its own folder, I don't have to copy the .py anywhere.

edit:  I see what you mean, I'll put it in a folder and archive it to fix the release, I have just been pulling my own repo so hadn't thought to test the release itself.

**Comment by ImmortalPie** [comment]
Ok trying to do this seems to have broken it, am out of time for the moment unfortunately Shall have another look later this evening.

**Comment by razvanab** [comment]
Sorry for bothering you with this. I think it required some sort of initialization for comfyui to load the extension from a folder.
https://github.com/Suzie1/ComfyUI_Guide_To_Making_Custom_Nodes/wiki/init-file

**Comment by ImmortalPie** [comment]
Ok It is working again now, unsure why it was working before without an init but does not now, strange.
Should be all good now though.

**Comment by razvanab** [comment]
Thank you.
